frontend/.gitignore
frontend/.vite/deps/_metadata.json
frontend/.vite/deps/package.json

[DRD-24](https://edu-team4-react24k.atlassian.net/browse/DRD-24?atlOrigin=eyJpIjoiNjZmZWQyZGRkNjc3NDNhZWI4ZmQ1NjNhYzM2NTkxODUiLCJwIjoiaiJ9
)
- Modified frontend .gitignore to include .vite folder
- stop frontend
- do npm run dev
- check that everything still works as expected

DRD-24: Modify frontend .gitignore to include .vite folder

---

mautic-lando/.gitignore

[DRD-29](https://edu-team4-react24k.atlassian.net/browse/DRD-29?atlOrigin=eyJpIjoiNDg0NjQ1NDgxYmJkNDgyODhmMzJkOTQ1MmU5MzgyYzAiLCJwIjoiaiJ9)
- Modified .gitignore in mautic-lando folder to omit files that don't need to be tracked
- If you have installed mautic-lando locally, you should see the number of changes go from 5K to on Source Control

DRD-29: Modify .gitignore in mautic-lando folder

---

frontend/src/pages/Contact.jsx

[DRD-38](https://edu-team4-react24k.atlassian.net/browse/DRD-38?atlOrigin=eyJpIjoiOTNjM2QyOTlmOWY0NDZjMGFhMDQ3NTg3YTc0NTNiOWMiLCJwIjoiaiJ9)
- Fix import of drupalLocalhostAddress in Contact.jsx
[DRD-38]: https://edu-team4-react24k.atlassian.net/browse/DRD-38?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-38: Fix import of drupalLocalhostAddress

---

frontend/src/components/HeroImage.jsx
frontend/src/components/ProseWrapper.jsx
frontend/src/components/Section.jsx
frontend/src/components/SectionHeading.jsx
frontend/src/pages/About.jsx
frontend/src/pages/Blog.jsx
frontend/src/pages/Contact.jsx
frontend/src/pages/OurServices.jsx

[DRD-46](https://edu-team4-react24k.atlassian.net/browse/DRD-46?atlOrigin=eyJpIjoiMjM2MWI0ZjI5ZTFkNDc3YzkwNmMyYTFlZDllOTYxOTIiLCJwIjoiaiJ9)
- Moved some jsx tags with tailwind styling to their own components
- Components created: Section, SectionHeading, HeroImage, ProseWrapper
- This way we can edit the styles just in the component, and changes are reflected on each page
- Notice that [DRD-50](https://edu-team4-react24k.atlassian.net/browse/DRD-50?atlOrigin=eyJpIjoiMjc4OTEyNzU4NDAxNDdmYzk5MGMxMzYyZGU5OGQ5YWUiLCJwIjoiaiJ9) is for implementing these components for the rest of the pages
- Test that the frontend pages render correctly without errors
[DRD-46]: https://edu-team4-react24k.atlassian.net/browse/DRD-46?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLW …

DRD-46: Refactor frontend to avoid repeated styles

---

frontend/src/components/Footer.jsx

Old Twitter logo changed to the new X logo; social media links added.

Druid social media links added

---

frontend/src/pages/Blog.jsx

[DRD-48](https://edu-team4-react24k.atlassian.net/browse/DRD-48?atlOrigin=eyJpIjoiM2MxMDRjZjc0OGU3NDBkZDlkYjBlNmQzMzExZDNkNzkiLCJwIjoiaiJ9)
- Corrected fetched json property from `name` to `display_name` in variable `const authorName`
- Check that blog posts show "admin" as author on front end
- We should also test creating another drupal user account, creating a blogpost with it and checking the correct author shows for that on frontend
[DRD-48]: https://edu-team4-react24k.atlassian.net/browse/DRD-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-48: corrected fetched json property from name to display_name

---

frontend/package-lock.json
frontend/package.json
frontend/src/pages/About.jsx
frontend/src/pages/Blog.jsx
frontend/src/pages/Contact.jsx
frontend/src/pages/FrontPage.jsx
frontend/src/pages/OurServices.jsx
frontend/src/pages/ServiceDetail.jsx

[DRD-53](https://edu-team4-react24k.atlassian.net/browse/DRD-53?atlOrigin=eyJpIjoiYWIzOTVkZGU0YzMzNDZhM2FjNDRmNjdhMjQ5MTk4MGUiLCJwIjoiaiJ9)
- Installed DOMPurify dependency
- Implemented sanitizing of html tagged content coming in from Drupal
- npm install (in frontend folder)
- Test that everything still renders on frontend
[DRD-53]: https://edu-team4-react24k.atlassian.net/browse/DRD-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-53: Implement DOMPurify to sanitize html tagged content coming in from Drupal

---

.gitignore
composer.json
composer.lock
vendor/mautic/api-library/lib/Api/Api.php

[DRD-39](https://edu-team4-react24k.atlassian.net/browse/DRD-39?atlOrigin=eyJpIjoiNjY0ZTE0ZDBhZGJjNGQ1MWIyNjEwNmFkYzBjOWI1MGYiLCJwIjoiaiJ9)
- Modified Api.php and added it as a tracked file to the repo
- Installed new dependencies mautic/api-library (probably redundant) and drupal/paragraphs
- `lando composer install` in root
- open drupal: Configuration > Web Services > Mautic integration:
1. Basic auth
2. http protocol
3. "Mautic base url" - run `lando info` in mautic-lando folder and look for appserver hostname. It's probably "appserver.mauticapp.internal"
4. HTTP Basic Authentication - input your admin credentials which you use to login to your mautic instance
5. Hit Connect to Mautic. At the bottom of the page you should see "Connection successfully established"
- …

DRD-39-1: Mautic Paragraph Configuration

---

frontend/src/components/Header.jsx

[DRD-16](https://edu-team4-react24k.atlassian.net/jira/software/projects/DRD/boards/1/backlog?selectedIssue=DRD-16)
- Added mobile menu toggle
- Hamburger icon
- Dynamic menu items
- Responsive styling enhancements
[DRD-16]: https://edu-team4-react24k.atlassian.net/browse/DRD-16?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update Header component with new changes

---

frontend/public/mautic-contact-form.html
frontend/src/components/MauticContactForm.jsx
frontend/src/css/MauticForm.css

[DRD-60](https://edu-team4-react24k.atlassian.net/browse/DRD-60?atlOrigin=eyJpIjoiNWYwZTQ4MDEwYzNhNDAwYjliOTRjNmFlMDg1YmFjYWQiLCJwIjoiaiJ9)
- Replaced iframe mautic form with the "self-hosted" version
- Created separate CSS file MauticForm.css which can be edited to style the form
- Must have imported mautic database from PR #29 
- Fill in the contact form on frontend and submit it, check you get the submission on Mautic
- You should see a new non anonymous contact (click off Toggle anonymous contacts)
- If you submit the form multiple times, the same Contact is updated (instead of creating a new contact)
- If form submission fails please check browser console for errors
- If the form is edited in the future (fields added/removed etc.) inside mautic, the html in …

DRD-60: Replace iframe mautic contact form with the "self-hosted" version

---

frontend/src/App.jsx
frontend/src/components/ProjectCard.jsx
frontend/src/components/ProjectContainer.jsx
frontend/src/pages/FrontPage.jsx
frontend/src/pages/ProjectCasePage.jsx

[DRD-80](https://edu-team4-react24k.atlassian.net/browse/DRD-80?atlOrigin=eyJpIjoiYmNlYjk2NDFjNjAxNGIzZTk2Mzc4OWE4OTFmODFkNmEiLCJwIjoiaiJ9)
- Created components ProjectContainer, ProjectCard
- Created page ProjectCasePage (dynamically created page for each project case)
- Fetched project_case data from Drupal to frontend
- When you click "Read more" you are taken to the individual project page
- **NOTICE:** Text paragraphs from the project_case node are rendered, **but image paragraphs are not**. Created new ticket ([DRD-81](https://edu-team4-react24k.atlassian.net/browse/DRD-81?atlOrigin=eyJpIjoiNWUyYWVmOTBjNzNiNDY2Mjk1NTZmYWU3NGY4ZjM2YjMiLCJwIjoiaiJ9)) to continue work on this.
- Check you see project cards rendered on front page
- Check links to individual project …

DRD-80: Fetch project cases an display project cards on frontend

---

frontend/src/App.jsx
frontend/src/components/MauticContactForm.jsx
frontend/src/pages/Contact.jsx
frontend/src/services/utils.js

[DRD-72](https://edu-team4-react24k.atlassian.net/browse/DRD-72?atlOrigin=eyJpIjoiZDllZjYxZGFiODBjNDFlY2FkOGUxZmY4ZTIzZGQ0N2UiLCJwIjoiaiJ9)
Also fixes [DRD-70](https://edu-team4-react24k.atlassian.net/browse/DRD-70?atlOrigin=eyJpIjoiMTI0NmQzMzAyMDQ0NGUyMjg0MDRlODA2OTgwMjU1MWIiLCJwIjoiaiJ9)
- Refactored MauticContactForm to never redirect after submission
- Added page titles for dynamic paths in App.jsx
- Added capitalizeFirstLetter function to Utils (used for creating dynamic path titles)
- Test form submission (with full data and required fields missing)
[DRD-72]: https://edu-team4-react24k.atlassian.net/browse/DRD-72?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DRD-70]: …

DRD-72: Fix contact form issues with redirecting

---

.env example
README.md
frontend/.env example

[DRD-52](https://edu-team4-react24k.atlassian.net/browse/DRD-52?atlOrigin=eyJpIjoiYmNjYjhmNmEwYmNhNDQ5ZWEzYTYzMmM0ZGI1YTQwMWIiLCJwIjoiaiJ9)
- Wrote a readme.md
- Added .env example files
- Read the readme
[DRD-52]: https://edu-team4-react24k.atlassian.net/browse/DRD-52?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-52: Write readme.md

---

composer.lock
web/sites/default/default.settings.php
web/sites/default/settings.php

[DRD-76](https://edu-team4-react24k.atlassian.net/jira/software/projects/DRD/boards/1?selectedIssue=DRD-76)
- Added configuration to web/sites/default/settings.php to add localhost as a trusted host to avoid errors/warnings on Drupal
- Updated core 
- lando composer install
- Check Drupal > Reports > Status report that there are no errors 
[DRD-76]: https://edu-team4-react24k.atlassian.net/browse/DRD-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-76: Configure trusted host settings

---

frontend/src/pages/About.jsx
frontend/src/services/utils.js
web/sites/default/settings.php

[DRD-86](https://edu-team4-react24k.atlassian.net/jira/software/projects/DRD/boards/1?selectedIssue=DRD-86)
- added the include in the jsonapi url to include the field_image and field_media_image inside field_about_us
- Edit the existing about us content in Drupal. Add new Text with Image and Image paragraphs in About us and save. 
- lando drush cr
- Check frontend About Us page that the images are rendering and that the console shows no errors. 
[DRD-86]: https://edu-team4-react24k.atlassian.net/browse/DRD-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-86: Fix image and text with image paragraph rendering

---

frontend/src/components/Footer.jsx

Implement changes to enhance the project footer in accordance with Figma style guide
Added JavaScript functionality
Checkout branch

DRD-101: Improved Footer according to Figma style guide.

---

frontend/src/components/Footer.jsx
frontend/src/components/ProjectContainer.jsx

[DRD-102](https://edu-team4-react24k.atlassian.net/browse/DRD-102?atlOrigin=eyJpIjoiNzdmYzg1YWE4M2Q3NGU1Zjg3ODIxYzg4MWNlNjIyZjgiLCJwIjoiaiJ9)
- Added id "featuredCases" to main div rendered by ProjectContainer.jsx
- Created function handleScrollToFeaturedCases for the "Featured cases" link in footer
- Clicking "Featured cases" link in footer (while on any page) should take you to frontpage section with featured cases
- Scroll to the page section should be smooth
[DRD-102]: https://edu-team4-react24k.atlassian.net/browse/DRD-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-102: Make footer "Featured cases" link scroll to featured cases

---

frontend/src/components/SectionHeading.jsx
frontend/src/css/AboutCards.css
frontend/src/pages/About.jsx

[DRD-107](https://edu-team4-react24k.atlassian.net/browse/DRD-107?atlOrigin=eyJpIjoiMTZmYjQxMGUwNTVmNDA1NzlmYjU4YjVlNjI4NWNiYTYiLCJwIjoiaiJ9)
- Styled About page cards to be mobile responsive (3 columns in large resolution, 1 column in small)
- Added some vertical margin to SectionHeading
- Test About page in different resolutions to check responsiveness
[DRD-107]: https://edu-team4-react24k.atlassian.net/browse/DRD-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-107: Fix About page cards mobile responsiveness

---

frontend/src/pages/Jobs.jsx
frontend/src/pages/OurServices.jsx

[DRD-113](https://edu-team4-react24k.atlassian.net/browse/DRD-113?atlOrigin=eyJpIjoiZDM3NGQ4NDc0ZmY5NDgwMDhiMDljYTRiMzlhZTgzMDEiLCJwIjoiaiJ9)
- Added right arrow icon to orange buttons on Services and Careers pages
- See that all three buttons look ok and have the right arrow icon
[DRD-113]: https://edu-team4-react24k.atlassian.net/browse/DRD-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-113: Add arrow icon to orange buttons

---

frontend/src/pages/Blog.jsx
frontend/src/pages/OurServices.jsx

[DRD-110](https://edu-team4-react24k.atlassian.net/jira/software/projects/DRD/boards/1?selectedIssue=DRD-110)
- Made a grid container and grid columns for blog posts
- Increased heading size and added h2 (hard-coded)
- Added some basic styling for Blog post cards and fixed some styling in the Services page too
- Check Blog page that blog posts are displayed in a grid
[DRD-110]: https://edu-team4-react24k.atlassian.net/browse/DRD-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-110: Add cards for blog posts in the blog page

---

frontend/src/components/Header.jsx

Header updated: fullscreen overlay menu and hamburger menu added.
Fixed navbar implemented to keep header and other components apart
Checkout branch

Drd 109: Hamburger menu and full screen overlay menu

---

frontend/src/App.jsx
frontend/src/pages/Blog.jsx
frontend/src/pages/FullBlogPost.jsx
frontend/src/pages/OurServices.jsx
frontend/src/pages/ServiceDetail.jsx

[DRD-114](https://edu-team4-react24k.atlassian.net/browse/DRD-114?atlOrigin=eyJpIjoiMWJkNjUzNjVlYWEzNDhkZGI1N2ZmMjdjZDU3ODJiNDQiLCJwIjoiaiJ9)
- Created individual paths (based on blog.id) for blog posts
- Moved FullBlogPost to it's own component
- Added back button to end of FullBlogPost
- Test that navigating to individual blog posts works and they have their own path
- Test back button works on blog post
[DRD-114]: https://edu-team4-react24k.atlassian.net/browse/DRD-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-114: Create paths for individual blog posts

---

README.md

[DRD-116](https://edu-team4-react24k.atlassian.net/browse/DRD-116?atlOrigin=eyJpIjoiZDM1OWNlZWM4MmMyNGM0ZDkxNDJjOTE0ZjFkNzM5YTIiLCJwIjoiaiJ9)
- Added Data Flow Diagram to readme
-
[DRD-116]: https://edu-team4-react24k.atlassian.net/browse/DRD-116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-116: Add Data Flow Diagram to readme

---

frontend/src/pages/Contact.jsx

[DRD-121](https://edu-team4-react24k.atlassian.net/browse/DRD-121?atlOrigin=eyJpIjoiZGNmMzM0MTYxMTY4NDM5Yjg3ZDhkZmY3Nzc5NjJkYmEiLCJwIjoiaiJ9)
- Styled Contact page so that text box and form stack in mobile resolutions
- Check Contact page in large and small resolutions
[DRD-121]: https://edu-team4-react24k.atlassian.net/browse/DRD-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-121: Style Contact page to be mobile responsive

---

frontend/src/components/MauticContactForm.jsx
frontend/src/components/ParagraphRenderer.jsx
frontend/src/pages/Blog.jsx
frontend/src/pages/Contact.jsx
frontend/src/pages/FrontPage.jsx
frontend/src/services/api.jsx
frontend/src/services/fetchContactSegments.jsx
frontend/src/services/utils.js

[DRD-69](https://edu-team4-react24k.atlassian.net/browse/DRD-69?atlOrigin=eyJpIjoiNmM3ZTIyMTlkYmJiNDA4MmFmYTViMjM5YjQyOGZlOGEiLCJwIjoiaiJ9)
- Commented out most console.logs (except for some error messages and the visitor segments for demo purposes if needed)
- You should only see console logs "Fetching contact segments for contactId:" and "Extracted Visitor Segment Names:"
[DRD-69]: https://edu-team4-react24k.atlassian.net/browse/DRD-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-69: Comment out console.logs

---

frontend/src/components/Section.jsx
frontend/src/pages/Blog.jsx

[DRD-123](https://edu-team4-react24k.atlassian.net/browse/DRD-123?atlOrigin=eyJpIjoiN2NmNDkyOGUxYTgwNDY1OTg5MTkxM2Y3MTc5NTc5ZjgiLCJwIjoiaiJ9)
- Refactored Blog page header to use Section and SectionHeading to match Services page header
- See that Blog page header and Services page header match
[DRD-123]: https://edu-team4-react24k.atlassian.net/browse/DRD-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-123: Style Blog page header to match Services page header

---

frontend/src/pages/Blog.jsx
frontend/src/pages/FrontPage.jsx

[DRD-122](https://edu-team4-react24k.atlassian.net/browse/DRD-122?atlOrigin=eyJpIjoiNmRjZjE3YjNmZWNlNDQ5YmE1MmRmMDA4ZDdmMTcxNjciLCJwIjoiaiJ9)
- Removed unused imports
- Commented out some useState variables that are no longer used
- You should no longer see vscode warnings about unused imports
[DRD-122]: https://edu-team4-react24k.atlassian.net/browse/DRD-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-122: Remove unused imports

---

frontend/src/pages/Blog.jsx

[DRD-123-1](https://edu-team4-react24k.atlassian.net/browse/DRD-123?atlOrigin=eyJpIjoiNTkyYjdjZTE4ZjkwNGZkZGI1MzdkZGQ5M2FhMmI3ZTAiLCJwIjoiaiJ9)
- Re-added import for SectionHeading in Blog page

DRD-123-1: Add import for SectionHeading

---

frontend/src/components/ProseWrapper.jsx
frontend/src/pages/Blog.jsx

[DRD-125](https://edu-team4-react24k.atlassian.net/browse/DRD-125?atlOrigin=eyJpIjoiOTk5YmYxNDBlMGMyNDM3N2E0YmU4M2JlODY1YWFjOTIiLCJwIjoiaiJ9)
- Styled blog cards to work better in mobile resolutions
- See Blog page in multiple resolutions
[DRD-125]: https://edu-team4-react24k.atlassian.net/browse/DRD-125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-125: Style blog cards

---

frontend/src/components/TextParagraph.jsx
frontend/src/components/TextWithImageParagraph.jsx
frontend/src/pages/ProjectCasePage.jsx
frontend/src/pages/ServiceDetail.jsx

[DRD-117](https://edu-team4-react24k.atlassian.net/jira/software/projects/DRD/boards/1?selectedIssue=DRD-117)
- centered text content on the Project case page
- added font size breakpoints
- added Back button
- changed content in Drupal
- centered text in ServiceDetail.jsx component
- Removed prosewrapper from text paragraph component
- lando db-import DRD-117.sql.gz
- check Project case pages and test button
[DRD-117]: https://edu-team4-react24k.atlassian.net/browse/DRD-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-117: Style Project Case pages

---

frontend/src/pages/ProjectCasePage.jsx

[DRD-126](https://edu-team4-react24k.atlassian.net/jira/software/projects/DRD/boards/1?selectedIssue=DRD-126)
- added font size breakpoints for project case description
- check project cases with different resolutions
[DRD-126]: https://edu-team4-react24k.atlassian.net/browse/DRD-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-126: add font size breakpoints for project case description

---

README.md

[DRD-91](https://edu-team4-react24k.atlassian.net/browse/DRD-91?atlOrigin=eyJpIjoiODcxYjU3ZjU1ODBhNGVlZmE0OGFiNmI0MjJkNjAzNWIiLCJwIjoiaiJ9)
- Updated readme (added screenshot, areas of improvement, dependencies used)
[DRD-91]: https://edu-team4-react24k.atlassian.net/browse/DRD-91?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-91: Update readme

---

frontend/src/pages/Blog.jsx
frontend/src/pages/OurServices.jsx

[DRD-124](https://edu-team4-react24k.atlassian.net/jira/software/projects/DRD/boards/1?selectedIssue=DRD-124)
- removed heroimage import from Blog.jsx
- added window.scrollTo(0, 0); to OurServices.jsx and Blog.jsx
- Navigate to Services page and Blog and check that it starts at the top of the page
[DRD-124]: https://edu-team4-react24k.atlassian.net/browse/DRD-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-124: Fix navigating to Services and Blog

---

frontend/src/components/ProjectCard.jsx
frontend/src/components/Section.jsx
frontend/src/components/TextParagraph.jsx
frontend/src/components/TextWithImageParagraph.jsx
frontend/src/pages/OurServices.jsx

[DRD-127](https://edu-team4-react24k.atlassian.net/browse/DRD-127?atlOrigin=eyJpIjoiMDJkMGQ1ZTk4N2EwNDAzMTkyMzAyMGQ4YmU3YTE2MDMiLCJwIjoiaiJ9)
- Fixed button alignment in Service page cards
- Increased vertical margins in certain components to make layout less cramped
- Check Services page cards look ok
- Check the added vertical margins look ok
[DRD-127]: https://edu-team4-react24k.atlassian.net/browse/DRD-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DRD-127: Enhance Read more button UI in Service page
